### ISSUE TITLE
MCM option to disable perfect block? 

### ISSUE THREAD

**Issue by peterpanning** [D7ry/valhallaCombat#1]
Hi. I was wondering if Valhalla might include an MCM option to disable the Perfect Block feature, and what configuration options it might have for the Exhausted state. 

I generally prefer parrying mechanics like in your other mod, Elden Parry (and Breath of the Wild), over timed Block mechanics as described in this mod's README (also present in Ordinator). 

I also find that the combination of the two is kind of silly. 

I'd love to use both Valhalla and Elden Parry, but if there were an option to disable the Perfect Block feature in Valhalla, I'm sure it would help the two feel better together. 

Please consider this a feature request, and let me know if there's any way I can help make it happen.

**Comment by D7ry** [comment]
Hi, Valhalla Combat comes with a highly customizable MCM that provides toggles for every single feature and sub-features. You can surely turn it off.
