### ISSUE TITLE
mcm中的限时格挡音效系统

### ISSUE THREAD

**Issue by gYdeHn** [D7ry/valhallaCombat#3]
在关闭该系统后限时格挡，完美格挡，回弹飞行物将不会有任何音效，能否让它恢复普通格挡的音效，或者丰富音效系统，为不同武器分发限时格挡和完美格挡音效，我只用sseedit能做到吗？
关闭，mod几个月前已经上传

**Comment by yhbj521** [comment]
> 在关闭该系统后限时格挡，完美格挡，回弹飞行物将不会有任何音效，能否让它恢复普通格挡的音效，或者丰富音效系统，为不同武器分发限时格挡和完美格挡音效，我只用sseedit能做到吗？
关闭，因为mod几个月前已经上传
